/**
 * IPC error code registry.
 *
 * Single source of truth for every error code that may flow back to the
 * renderer via `IpcResponse`. Use the `ipcError` helper in
 * `src/main/ipc/_kit/errors.ts` to construct errors from these codes.
 */
export const IpcErrorCodes = {
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  STREAM_INIT_FAILED: "STREAM_INIT_FAILED",

  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_REQUIRED: "PROJECT_REQUIRED",
  PROJECT_PATH_MISSING: "PROJECT_PATH_MISSING",

  CHAT_SESSION_NOT_FOUND: "CHAT_SESSION_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",

  PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_INVALID: "PLAN_INVALID",
  APPLY_RUN_NOT_FOUND: "APPLY_RUN_NOT_FOUND",
  APPLY_RUN_NOT_READY: "APPLY_RUN_NOT_READY",
  APPLY_SESSION_NOT_READY: "APPLY_SESSION_NOT_READY",
  APPLY_RUN_PERSIST_FAILED: "APPLY_RUN_PERSIST_FAILED",
  STAGE_NOT_FOUND: "STAGE_NOT_FOUND",
  STAGE_TYPE_NOT_IMPLEMENTED: "STAGE_TYPE_NOT_IMPLEMENTED",

  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  INVALID_WORKFLOW_NAME: "INVALID_WORKFLOW_NAME",
  BUILT_IN_WORKFLOW: "BUILT_IN_WORKFLOW",

  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  ACP_ERROR: "ACP_ERROR",
  ACP_NOT_READY: "ACP_NOT_READY",
  ACP_EXIT_GIVEUP: "ACP_EXIT_GIVEUP",
  PROMPT_CAPABILITY_MISMATCH: "PROMPT_CAPABILITY_MISMATCH",
  SPAWN_ERROR: "SPAWN_ERROR",
  CONFIG_OPTION_NOT_SUPPORTED: "CONFIG_OPTION_NOT_SUPPORTED",
  CONFIG_OPTION_INVALID_VALUE: "CONFIG_OPTION_INVALID_VALUE",
  RELEASE_CHECK_FAILED: "RELEASE_CHECK_FAILED",
  RELEASE_VERSION_INVALID: "RELEASE_VERSION_INVALID",

  // ACP agent install / uninstall (installer.ts). Surfaced to the renderer so
  // the install UI can show a precise reason; without registration here
  // wrapHandler would squash them to UNKNOWN_ERROR and mis-log normal install
  // failures (e.g. missing Node) as unhandled errors.
  INVALID_DISTRIBUTION: "INVALID_DISTRIBUTION",
  ENV_MISSING: "ENV_MISSING",
  INSTALL_FAILED: "INSTALL_FAILED",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  PLATFORM_UNSUPPORTED: "PLATFORM_UNSUPPORTED",
  INVALID_AGENT_ID: "INVALID_AGENT_ID",
  UNINSTALL_FAILED: "UNINSTALL_FAILED",
  INSTALL_BUSY: "INSTALL_BUSY",

  YUNXIAO_API_ERROR: "YUNXIAO_API_ERROR",
  INTEGRATION_PROVIDER_NOT_SUPPORTED: "INTEGRATION_PROVIDER_NOT_SUPPORTED",
  INTEGRATION_PROVIDER_NOT_CONNECTED: "INTEGRATION_PROVIDER_NOT_CONNECTED",
  INTEGRATION_RESOURCE_TYPE_NOT_SUPPORTED: "INTEGRATION_RESOURCE_TYPE_NOT_SUPPORTED",
} as const;

export type IpcErrorCode = (typeof IpcErrorCodes)[keyof typeof IpcErrorCodes];
